[package]
name = "apex-ast"
version = "0.1.0"
authors = ["Ryan Faulhaber <faulhaberryan@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
pest = "^2.1.1"
pest_derive = "^2.1.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
# add for benchmarking:
# criterion = "0.2.11"